version: '3.7'

# This override file should be used in development environments to
# bind-mount the app from the host into the container

services:
  amqp-send-test:
    command: >
      sh -c "scripts/wait-for.sh amqp-send-test-message:8161 -- tail -f /dev/null"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    depends_on: 
      - amqp-send-test-message
    environment: 
      MESSAGE_HOST: amqp-send-test-message
      MESSAGE_PORT: 5672
      MESSAGE_USERNAME: artemis
      MESSAGE_PASSWORD: artemis
      MESSAGE_TRANSPORT: tcp
      MESSAGE_QUEUE: test-queue

  amqp-send-test-message:
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "8161:8161"
      - "5672:5672"
    volumes:
      - message-queue-data:/var/lib/artemis/data
      - message-queue-tmp:/var/lib/artemis/tmp
      - message-queue-etc:/var/lib/artemis/etc
      - message-queue-etc-override:/var/lib/artemis/etc-override
      - message-queue-lock:/var/lib/artemis/lock

volumes:
  node_modules:
  message-queue-data: {}
  message-queue-tmp: {}
  message-queue-etc: {}
  message-queue-etc-override: {}
  message-queue-lock: {}
